// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission_4.Models;

namespace Mission_4.Migrations
{
    [DbContext(typeof(MovieFromContext))]
    [Migration("20220222221949_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission_4.Models.FormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Category = "Comedy",
                            Director = "John Hughes",
                            Edited = false,
                            Rating = "PG13",
                            Title = "Ferris Bueller's Day Off",
                            Year = 1986
                        },
                        new
                        {
                            FormId = 2,
                            Category = "Comedy/Drama",
                            Director = "Taika Waititi",
                            Edited = false,
                            Rating = "PG13",
                            Title = "Jojo Rabbit",
                            Year = 2019
                        },
                        new
                        {
                            FormId = 3,
                            Category = "Comedy",
                            Director = "Danny Boyle",
                            Edited = false,
                            Rating = "PG13",
                            Title = "Yesterday",
                            Year = 2019
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
